[Interface]
Address = 10.13.13.3
PrivateKey = mORbTuoIEbe4mum+f9joFaFHg36QQejuS7zDuocXzFA=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = BTvEV8D4UY+WMs7wvzqhsCFpP9a+L4uabyJRL0ct5So=
PresharedKey = I9A5hhNd0Egaikuq+VRyuTwnIgmJvgAdgOgh+Z/OBWQ=
Endpoint = sharpishly.vm:51820
AllowedIPs = 0.0.0.0/0, ::/0
