[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = eM1Dl2ra11qdrJEiJsrAEV3gNwfxdh06+H05Jxcb71Y=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_myphone
PublicKey = w58mSQXiaDLKDpVbyfKyY8U39XGSvCCITxHtZrFOuyY=
PresharedKey = TxsC3b6ppHAFKIqtJJmm+dI/SSu+9jUQaptIBESrbOY=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer_mylaptop
PublicKey = rOJwoxss5Mejhr1EQnAAIBpMmckvEtRis+tTgA5oKCo=
PresharedKey = I9A5hhNd0Egaikuq+VRyuTwnIgmJvgAdgOgh+Z/OBWQ=
AllowedIPs = 10.13.13.3/32

