[Interface]
Address = 10.13.13.2
PrivateKey = kEe0ertNkzsm07iRKe+mSUNW9J9ZJ/CnwCRQrRtVoFY=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = BTvEV8D4UY+WMs7wvzqhsCFpP9a+L4uabyJRL0ct5So=
PresharedKey = TxsC3b6ppHAFKIqtJJmm+dI/SSu+9jUQaptIBESrbOY=
Endpoint = sharpishly.vm:51820
AllowedIPs = 0.0.0.0/0, ::/0
