<?php
// Location: /var/www/html/php/src/worker-daemon.php

declare(strict_types=1);

require_once __DIR__ . '/autoload.php';

use App\Services\Logger;
use App\Services\CsvProcessor;
use App\Db;

// Safety Constraints
$maxIterations = 1000; 
$iteration = 0;
$memoryLimit = 128 * 1024 * 1024; // 128MB
$queueDir = __DIR__ . '/../../storage/queue/';

Logger::info("Neural Factory Daemon Online", ['pid' => getmypid()], 'scheduler');

while ($iteration < $maxIterations) {
    $iteration++;

    try {
        $db = new Db();

        // --- 1. FILE-BASED QUEUE (CSV & Jobs) ---
        // Look for .job files generated by your CsvController
        $jobFiles = glob($queueDir . '*.job');

        foreach ($jobFiles as $jobFile) {
            $rawContent = file_get_contents($jobFile);
            $jobData = json_decode($rawContent, true);
            
            if ($jobData && isset($jobData['job_id'], $jobData['filepath'])) {
                Logger::info("Processing Job #{$jobData['job_id']}", ['file' => $jobData['filepath']]);

                // Instantiate the processor we just fixed
                $processor = new CsvProcessor();
                
                // Call the correct method name: process()
                $processor->process(
                    (int)$jobData['job_id'], 
                    (string)$jobData['filepath']
                );

                // Cleanup: Remove job file so it doesn't loop
                unlink($jobFile);
            } else {
                Logger::error("Invalid job file format", ['file' => $jobFile]);
                // Move invalid jobs out of the way
                rename($jobFile, $jobFile . '.bad');
            }
        }

        // --- 2. SQL-BASED TASKS (Cron entries) ---
        $tasks = $db->find([
            'tbl'   => 'tasks',
            'where' => ['status' => 'active', 'type' => 'cron'],
        ]);
        // Note: You can implement shouldRunNow() here for DB-based scheduling

        // --- 3. HEALTH HEARTBEAT ---
        file_put_contents($queueDir . 'health.json', json_encode([
            'status' => 'running',
            'iteration' => $iteration,
            'memory_peak' => memory_get_peak_usage(true),
            'last_run' => date('c')
        ]));

    } catch (Throwable $e) {
        Logger::exception($e, 'scheduler');
    }

    // Memory Guard: Exit and let Docker/Cron restart us if leaking
    if (memory_get_usage(true) > $memoryLimit) {
        Logger::info("Memory limit reached. Cycling daemon...", [], 'scheduler');
        break; 
    }

    // Hibernate for 5 seconds to save CPU
    sleep(5);
}

Logger::info("Daemon reached iteration limit. Restarting...");
exit(0);