; Optimize for low-resource VM
memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300

; OpCache for lightning-fast script execution
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.validate_timestamps=1

file_uploads = On

# upload_max_filesize = 1G
# post_max_size = 1G
# memory_limit = 512M
max_execution_time = 0
max_input_time = 0