name: Lint Standalone JavaScript

on:
  pull_request:
    branches:
      - main # or your default branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint (using a specific version to avoid node)
        run: |
          curl -sLO https://registry.npmjs.org/eslint/-/eslint-8.56.0.tgz #or latest version
          tar -xzf eslint-8.56.0.tgz
          ./package/bin/eslint --version #verify it works

      - name: Configure ESLint (if needed)
        run: |
          if [ ! -f .eslintrc.js ]; then
            echo "module.exports = { extends: 'eslint:recommended', env: { browser: true, es2021: true } };" > .eslintrc.js
          fi

      - name: Lint script.js
        run: ./package/bin/eslint script.js